// ============================================================
//  drshyam — COMPLETE DATA LAYER
//  Multi-source: youtube | drive | direct | vimeo | cloudflare
// ============================================================

function daysAgo(n){ return new Date(Date.now()-n*864e5).toISOString(); }
function hoursAgo(n){ return new Date(Date.now()-n*36e5).toISOString(); }

const CHANNELS = [
  { id:"ch1",  name:"TechVision",    handle:"@techvision",    avatar:"TV", color:"#00D4FF", subscribers:4800000, verified:true,  category:"Technology",
    description:"Exploring the frontiers of technology — AI, quantum computing and the innovations shaping tomorrow." },
  { id:"ch2",  name:"CineWorld",     handle:"@cineworld",     avatar:"CW", color:"#FF6B35", subscribers:2100000, verified:true,  category:"Film",
    description:"Film reviews, director spotlights and deep dives into cinema history." },
  { id:"ch3",  name:"NatureLens",    handle:"@naturelens",    avatar:"NL", color:"#22C55E", subscribers:3400000, verified:true,  category:"Nature",
    description:"Award-winning nature documentaries and 4K wildlife footage from every corner of the planet." },
  { id:"ch4",  name:"CodeCraft",     handle:"@codecraft",     avatar:"CC", color:"#A855F7", subscribers:1900000, verified:true,  category:"Education",
    description:"Full-stack tutorials, system design, coding interviews and career advice for developers." },
  { id:"ch5",  name:"MusicWave",     handle:"@musicwave",     avatar:"MW", color:"#F59E0B", subscribers:6700000, verified:true,  category:"Music",
    description:"Official music videos, live sessions, artist interviews and genre explorations." },
  { id:"ch6",  name:"FoodieHub",     handle:"@foodiehub",     avatar:"FH", color:"#EF4444", subscribers:890000,  verified:false, category:"Food",
    description:"Recipes, restaurant tours, street food adventures and culinary science." },
  { id:"ch7",  name:"SportsPulse",   handle:"@sportspulse",   avatar:"SP", color:"#06B6D4", subscribers:5200000, verified:true,  category:"Sports",
    description:"Match highlights, athlete interviews, tactical analysis and sports science." },
  { id:"ch8",  name:"MindSpace",     handle:"@mindspace",     avatar:"MS", color:"#8B5CF6", subscribers:720000,  verified:false, category:"Wellness",
    description:"Meditation, mental health, productivity science and the psychology of happiness." },
  { id:"ch9",  name:"HistoryVault",  handle:"@historyvault",  avatar:"HV", color:"#D97706", subscribers:1600000, verified:true,  category:"History",
    description:"Uncovering forgotten stories — ancient civilisations, wars, revolutions." },
  { id:"ch10", name:"GameRealm",     handle:"@gamerealm",     avatar:"GR", color:"#10B981", subscribers:3800000, verified:true,  category:"Gaming",
    description:"Game reviews, walkthroughs, developer interviews and the culture of gaming." },
  { id:"ch11", name:"ScienceDaily",  handle:"@sciencedaily",  avatar:"SD", color:"#3B82F6", subscribers:2800000, verified:true,  category:"Science",
    description:"Breaking science news, research explainers and interviews with leading researchers." },
  { id:"ch12", name:"TravelDiaries", handle:"@traveldiaries", avatar:"TD", color:"#F97316", subscribers:1100000, verified:false, category:"Travel",
    description:"Cinematic travel vlogs, destination guides and tips for the modern explorer." },
];

const VIDEOS = [
  { id:"v1",  channelId:"ch1",  title:"The Future of AI: What Happens in the Next 10 Years",
    description:"A deep dive into artificial intelligence trends, from large language models to autonomous systems. We explore what experts predict for the next decade.\n\n00:00 Introduction\n02:30 Current state of AI\n06:45 LLMs and what's next\n12:00 AI in healthcare\n15:30 The jobs question\n18:00 Conclusion",
    thumbnail:"https://picsum.photos/seed/ai1/640/360", src:{type:"youtube",id:"kCc8FmEb1nY"},
    duration:"18:42", views:4200000, likes:187000, dislikes:3400, comments:14200,
    uploadedAt:hoursAgo(6),  tags:["AI","technology","future","machine learning"], category:"Technology", isShort:false, isLive:false },
  { id:"v2",  channelId:"ch4",  title:"Build a Full-Stack App in 1 Hour — React + Node.js",
    description:"Complete tutorial: build and deploy a production-ready full-stack application from scratch. Covers React hooks, REST APIs, authentication and Vercel.\n\n00:00 Setup\n08:00 Backend\n24:00 React frontend\n44:00 Auth\n54:00 Deploy",
    thumbnail:"https://picsum.photos/seed/code2/640/360", src:{type:"youtube",id:"b9eMGE7QtTk"},
    duration:"58:14", views:1800000, likes:92000, dislikes:1200, comments:6800,
    uploadedAt:daysAgo(3),   tags:["react","nodejs","tutorial","webdev"], category:"Education", isShort:false, isLive:false },
  { id:"v3",  channelId:"ch1",  title:"Quantum Computing Explained — No Physics Degree Required",
    description:"Qubits, superposition, entanglement — all broken down with real-world analogies and stunning visuals.",
    thumbnail:"https://picsum.photos/seed/quantum3/640/360", src:{type:"youtube",id:"JhHMJCUmq28"},
    duration:"22:08", views:3100000, likes:142000, dislikes:2100, comments:9400,
    uploadedAt:daysAgo(14),  tags:["quantum","computing","science","technology"], category:"Technology", isShort:false, isLive:false },
  { id:"v4",  channelId:"ch11", title:"James Webb Telescope: Every Mind-Blowing Discovery So Far",
    description:"The JWST has revolutionised our understanding of the universe. This video covers every major discovery from its first year.",
    thumbnail:"https://picsum.photos/seed/jwst4/640/360", src:{type:"youtube",id:"4C_GpEMObxc"},
    duration:"31:55", views:8900000, likes:410000, dislikes:5600, comments:32000,
    uploadedAt:daysAgo(20),  tags:["space","telescope","NASA","science"], category:"Science", isShort:false, isLive:false },
  { id:"v5",  channelId:"ch3",  title:"Deep Ocean Mysteries: Creatures Never Seen Before",
    description:"Marine biologists captured footage of species previously unknown to science at depths of 4,000 meters.",
    thumbnail:"https://picsum.photos/seed/ocean5/640/360", src:{type:"youtube",id:"YE7VzlLtp-4"},
    duration:"45:30", views:7800000, likes:364000, dislikes:4200, comments:28000,
    uploadedAt:daysAgo(7),   tags:["ocean","nature","marine life","documentary"], category:"Nature", isShort:false, isLive:false },
  { id:"v6",  channelId:"ch3",  title:"Arctic Wolf Pack Hunting — Breathtaking 4K Wildlife",
    description:"Witness the extraordinary teamwork of an Arctic wolf pack hunting caribou across the frozen tundra.",
    thumbnail:"https://picsum.photos/seed/wolf6/640/360", src:{type:"youtube",id:"08p3mxEGkDo"},
    duration:"28:17", views:5400000, likes:248000, dislikes:2800, comments:18000,
    uploadedAt:daysAgo(11),  tags:["wolves","arctic","wildlife","4K","nature"], category:"Nature", isShort:false, isLive:false },
  { id:"v7",  channelId:"ch5",  title:"Orchestra Plays Interstellar — Live at Royal Albert Hall",
    description:"Breathtaking live performance of Hans Zimmer's Interstellar score by the London Philharmonic.",
    thumbnail:"https://picsum.photos/seed/orch7/640/360", src:{type:"youtube",id:"UDVtMYqUAyw"},
    duration:"1:04:22", views:22000000, likes:980000, dislikes:8000, comments:64000,
    uploadedAt:daysAgo(45),  tags:["orchestral","Zimmer","live","classical","music"], category:"Music", isShort:false, isLive:false },
  { id:"v8",  channelId:"ch5",  title:"Lo-Fi Hip Hop — Study & Chill Beats 24/7 🔴 LIVE",
    description:"Relaxing lo-fi beats for studying, working and chilling. Continuous stream with no ads.",
    thumbnail:"https://picsum.photos/seed/lofi8/640/360", src:{type:"youtube",id:"jfKfPfyJRdk"},
    duration:"LIVE", views:18000000, likes:740000, dislikes:12000, comments:48000,
    uploadedAt:hoursAgo(2),  tags:["lofi","study","chill","beats","music"], category:"Music", isShort:false, isLive:true },
  { id:"v9",  channelId:"ch10", title:"Elden Ring — Full Story Explained (All Endings)",
    description:"Complete lore of Elden Ring explained — every character, every ending, every hidden connection.",
    thumbnail:"https://picsum.photos/seed/elden9/640/360", src:{type:"youtube",id:"Jx8z_MdLiF8"},
    duration:"2:14:08", views:11000000, likes:520000, dislikes:6200, comments:74000,
    uploadedAt:daysAgo(60),  tags:["elden ring","gaming","lore","fromsoft","RPG"], category:"Gaming", isShort:false, isLive:false },
  { id:"v10", channelId:"ch10", title:"Top 10 Most Anticipated Games of 2025",
    description:"Every major game releasing in 2025 ranked and reviewed — from AAA blockbusters to indie darlings.",
    thumbnail:"https://picsum.photos/seed/games10/640/360", src:{type:"youtube",id:"PVBQLvl8h7A"},
    duration:"24:38", views:3200000, likes:156000, dislikes:4100, comments:22000,
    uploadedAt:daysAgo(9),   tags:["games","2025","upcoming","gaming"], category:"Gaming", isShort:false, isLive:false },
  { id:"v11", channelId:"ch4",  title:"System Design Interview — How to Design Netflix",
    description:"Complete walkthrough of how to design a video streaming platform. CDN, encoding, databases and scaling.",
    thumbnail:"https://picsum.photos/seed/sysdes11/640/360", src:{type:"youtube",id:"psQzyFfsUGU"},
    duration:"43:20", views:2600000, likes:128000, dislikes:1800, comments:9200,
    uploadedAt:daysAgo(22),  tags:["system design","interview","netflix","backend"], category:"Education", isShort:false, isLive:false },
  { id:"v12", channelId:"ch8",  title:"The Science of Deep Work — How to Focus for 4 Hours Straight",
    description:"Based on Cal Newport's research — the neuroscience behind deep focus and a step-by-step system for flow state.",
    thumbnail:"https://picsum.photos/seed/focus12/640/360", src:{type:"youtube",id:"ZD7dXfdDPfg"},
    duration:"19:44", views:4800000, likes:224000, dislikes:2900, comments:16000,
    uploadedAt:daysAgo(18),  tags:["productivity","focus","deep work","psychology"], category:"Wellness", isShort:false, isLive:false },
  { id:"v13", channelId:"ch7",  title:"Top 50 Goals in Football History — 4K Remastered",
    description:"The 50 greatest goals ever scored in world football, remastered in 4K. Maradona, Ronaldo, Messi, Zidane.",
    thumbnail:"https://picsum.photos/seed/goals13/640/360", src:{type:"youtube",id:"rQMKnYMNsyQ"},
    duration:"38:50", views:34000000, likes:1400000, dislikes:22000, comments:88000,
    uploadedAt:daysAgo(35),  tags:["football","goals","soccer","messi","4K"], category:"Sports", isShort:false, isLive:false },
  { id:"v14", channelId:"ch7",  title:"NBA Greatest Dunks — Full Compilation 2024",
    description:"Every jaw-dropping dunk from the 2024 NBA season. Slow-motion replays, commentary and fan reactions.",
    thumbnail:"https://picsum.photos/seed/nba14/640/360", src:{type:"youtube",id:"OoVi1MiNHyQ"},
    duration:"22:15", views:9100000, likes:398000, dislikes:7400, comments:41000,
    uploadedAt:daysAgo(4),   tags:["NBA","basketball","dunks","sports","2024"], category:"Sports", isShort:false, isLive:false },
  { id:"v15", channelId:"ch9",  title:"The Fall of the Roman Empire — What Really Happened",
    description:"Using the latest archaeological evidence and primary sources, the definitive story of Rome's collapse.",
    thumbnail:"https://picsum.photos/seed/rome15/640/360", src:{type:"youtube",id:"OP9KLRQ5UFM"},
    duration:"1:02:18", views:6200000, likes:282000, dislikes:3800, comments:44000,
    uploadedAt:daysAgo(28),  tags:["rome","history","ancient","documentary"], category:"History", isShort:false, isLive:false },
  { id:"v16", channelId:"ch6",  title:"Tokyo Street Food Tour — 50 Dishes in 10 Hours",
    description:"We ate our way through Tokyo's best street food markets, izakayas and ramen shops.",
    thumbnail:"https://picsum.photos/seed/tokyo16/640/360", src:{type:"youtube",id:"iNbKqfALRy0"},
    duration:"52:40", views:8700000, likes:396000, dislikes:5100, comments:52000,
    uploadedAt:daysAgo(16),  tags:["food","tokyo","japan","street food","travel"], category:"Food", isShort:false, isLive:false },
  { id:"v17", channelId:"ch12", title:"Exploring the Hidden Villages of Patagonia",
    description:"Deep in Argentine Patagonia, we discover communities untouched by tourism.",
    thumbnail:"https://picsum.photos/seed/pat17/640/360", src:{type:"youtube",id:"2Y8qKE4SKuY"},
    duration:"34:28", views:2900000, likes:138000, dislikes:1600, comments:11000,
    uploadedAt:daysAgo(12),  tags:["patagonia","travel","argentina","adventure"], category:"Travel", isShort:false, isLive:false },
  { id:"v18", channelId:"ch11", title:"We Finally Know What's Inside a Black Hole",
    description:"New theoretical physics research gives us the closest look yet at black hole interiors.",
    thumbnail:"https://picsum.photos/seed/bh18/640/360", src:{type:"youtube",id:"S_GVbuddri8"},
    duration:"26:44", views:14000000, likes:620000, dislikes:8200, comments:68000,
    uploadedAt:daysAgo(8),   tags:["black hole","space","physics","science"], category:"Science", isShort:false, isLive:false },
  /* ── SHORTS ── */
  { id:"v19", channelId:"ch1",  title:"AI Generated This App in 3 Seconds 🤯 #shorts",
    description:"Watch GPT-4o generate a full working app in real time.",
    thumbnail:"https://picsum.photos/seed/s1/360/640", src:{type:"youtube",id:"yAyFnBKBMig"},
    duration:"0:58", views:28000000, likes:1200000, dislikes:15000, comments:92000,
    uploadedAt:hoursAgo(14), tags:["AI","shorts","viral","GPT"], category:"Technology", isShort:true, isLive:false },
  { id:"v20", channelId:"ch7",  title:"Ronaldo's Insane Free Kick 🔥 #shorts",
    description:"Best free kick of the decade.",
    thumbnail:"https://picsum.photos/seed/s2/360/640", src:{type:"youtube",id:"U0QNQMU_3hM"},
    duration:"0:32", views:42000000, likes:1900000, dislikes:28000, comments:140000,
    uploadedAt:hoursAgo(8),  tags:["ronaldo","football","shorts","viral"], category:"Sports", isShort:true, isLive:false },
  { id:"v21", channelId:"ch4",  title:"One Line of Code That Does Everything #shorts",
    description:"The most powerful single line of JavaScript you'll ever write.",
    thumbnail:"https://picsum.photos/seed/s3/360/640", src:{type:"youtube",id:"TNpispMc5sA"},
    duration:"0:45", views:18000000, likes:820000, dislikes:9000, comments:44000,
    uploadedAt:hoursAgo(20), tags:["coding","shorts","javascript"], category:"Education", isShort:true, isLive:false },
  { id:"v22", channelId:"ch3",  title:"Baby Elephant's First Steps 🐘 #shorts",
    description:"Heartwarming footage of a newborn elephant.",
    thumbnail:"https://picsum.photos/seed/s4/360/640", src:{type:"youtube",id:"PdNKjsDCGao"},
    duration:"0:47", views:64000000, likes:2800000, dislikes:18000, comments:180000,
    uploadedAt:daysAgo(2),   tags:["elephant","shorts","cute","wildlife"], category:"Nature", isShort:true, isLive:false },
  /* ── GOOGLE DRIVE EXAMPLE ── */
  { id:"v23", channelId:"ch8",  title:"Morning Meditation for Clarity (Google Drive Demo)",
    description:"Example: Google Drive hosted video.\n\nTo use your own:\n1. Upload to Drive → Share → Anyone with link\n2. Copy the File ID from the URL\n3. Set src: { type:'drive', id:'YOUR_FILE_ID' }",
    thumbnail:"https://picsum.photos/seed/med23/640/360", src:{type:"drive",id:"1u_p8kKuAQFHcxwrAiHGAcV7tgimEPwsX"},
    duration:"10:00", views:980000, likes:48000, dislikes:400, comments:3200,
    uploadedAt:daysAgo(6),   tags:["meditation","wellness","drive"], category:"Wellness", isShort:false, isLive:false },
  /* ── DIRECT MP4 ── */
  { id:"v24", channelId:"ch9",  title:"Big Buck Bunny (Direct .mp4 Demo)",
    description:"Example: Direct .mp4 video from any CDN/host.\n\nTo use your own:\nSet src: { type:'direct', url:'https://yourcdn.com/video.mp4' }\n\nWorks with: AWS S3, Firebase Storage, Bunny CDN, Cloudflare R2.",
    thumbnail:"https://picsum.photos/seed/bbb24/640/360", src:{type:"direct",url:"https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"},
    duration:"9:56", views:340000, likes:18000, dislikes:200, comments:1400,
    uploadedAt:daysAgo(3),   tags:["demo","direct","mp4","sample"], category:"History", isShort:false, isLive:false },
];

const CATEGORIES = [
  {id:"all",label:"All",icon:"🏠"},{id:"Technology",label:"Technology",icon:"💻"},
  {id:"Science",label:"Science",icon:"🔬"},{id:"Gaming",label:"Gaming",icon:"🎮"},
  {id:"Music",label:"Music",icon:"🎵"},{id:"Sports",label:"Sports",icon:"⚽"},
  {id:"Nature",label:"Nature",icon:"🌿"},{id:"Education",label:"Education",icon:"📚"},
  {id:"Food",label:"Food",icon:"🍜"},{id:"Travel",label:"Travel",icon:"✈️"},
  {id:"History",label:"History",icon:"🏛️"},{id:"Wellness",label:"Wellness",icon:"🧘"},
  {id:"Shorts",label:"Shorts",icon:"⚡"},{id:"Live",label:"Live Now",icon:"🔴"},
];

const SAMPLE_COMMENTS = {
  v1:[
    {id:"c1",name:"Dr. Shyam",avatar:"DS",color:"#FF6B35",text:"This is the most comprehensive AI overview I've seen. The section on job displacement is particularly eye-opening.",likes:4820,time:hoursAgo(5),replies:[
      {id:"c1r1",name:"Priya R.",avatar:"PR",color:"#A855F7",text:"The healthcare section blew my mind. The diagnostic accuracy stats are staggering.",likes:892,time:hoursAgo(4)},
      {id:"c1r2",name:"Alex Chen",avatar:"AC",color:"#22C55E",text:"What about AI safety? That's the real conversation we need to be having.",likes:1240,time:hoursAgo(3)},
    ]},
    {id:"c2",name:"Dev K.",avatar:"DK",color:"#00D4FF",text:"I've been following AI development for 15 years. This video gets the nuances right in a way most coverage doesn't.",likes:3100,time:hoursAgo(5),replies:[]},
    {id:"c3",name:"Anika J.",avatar:"AJ",color:"#8B5CF6",text:"Pinning this for my CS students. Required viewing.",likes:2280,time:hoursAgo(3),replies:[]},
  ],
  v5:[
    {id:"c4",name:"Maria L.",avatar:"ML",color:"#F59E0B",text:"The anglerfish segment made me genuinely uncomfortable. The ocean truly is alien.",likes:8920,time:daysAgo(6),replies:[
      {id:"c4r1",name:"Riya S.",avatar:"RS",color:"#EF4444",text:"And to think we've only explored 5% of the ocean floor... what else is down there?",likes:2140,time:daysAgo(6)},
    ]},
    {id:"c5",name:"Omar F.",avatar:"OF",color:"#D97706",text:"I'm a marine biologist and this documentary is shockingly accurate. Very rare for mainstream media.",likes:12400,time:daysAgo(7),replies:[]},
  ],
  v13:[
    {id:"c6",name:"Tom W.",avatar:"TW",color:"#10B981",text:"Maradona's goal against England at 26:40 still gives me chills every single time. Greatest moment in sports history.",likes:18400,time:daysAgo(34),replies:[]},
    {id:"c7",name:"Dr. Shyam",avatar:"DS",color:"#FF6B35",text:"The 4K remaster of Zidane's volley in the Champions League final is just unbelievable quality.",likes:9200,time:daysAgo(33),replies:[]},
  ],
};
